spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: r1
            uri: http://localhost:8081/
            predicates:
              - path=/api/v1/user/**
          - id: r2
            uri: http://localhost:8081/
            predicates:
              - path=/api/v1/address/**

          - id: r3
            uri: http://localhost:8082/
            predicates:
              - path=/api/v1/orders/**
          - id: r4
            uri: http://localhost:8082/
            predicates:
              - path=/api/v1/order-items/**

          - id: r5
            uri: http://localhost:8083/
            predicates:
              - path=/api/v1/products/**
              -
          - id: r6
            uri: http://localhost:8083/
            predicates:
              - path=/api/v1/categories/**

          - id: r7
            uri: http://localhost:8084/
            predicates:
              - path=/api/v1/payments/**

          - id: r8
            uri: http://localhost:8085/
            predicates:
              - path=/api/v1/notifications/**



  application:
    name: gateway-service
server:
  port: 8888