spring:
    application:
      name: notification-service
    config:
      import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}
    # spring:
    #   config:
    #     import: optional:configserver:http://localhost:9999
server:
  port: 8085